"""add ondete foreginker at table interest_rates

Revision ID: 322c472ab14f
Revises: 88e742dd9deb
Create Date: 2026-04-03 23:00:37.755484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322c472ab14f'
down_revision: Union[str, None] = '88e742dd9deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interest_rates', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('interest_rates_bank_id_fkey', 'interest_rates', type_='foreignkey')
    op.create_foreign_key(None, 'interest_rates', 'banks', ['bank_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interest_rates', type_='foreignkey')
    op.create_foreign_key('interest_rates_bank_id_fkey', 'interest_rates', 'banks', ['bank_id'], ['id'])
    op.alter_column('interest_rates', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
