"""add field channel for table interest_rate

Revision ID: 65ac863ab0f9
Revises: 38be17c9c653
Create Date: 2026-05-03 16:34:32.058298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ac863ab0f9'
down_revision: Union[str, None] = '38be17c9c653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_rates', sa.Column('channel', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE interest_rates SET channel = 'COUNTER' WHERE channel IS NULL")

    op.alter_column('interest_rates', 'channel', nullable=False)




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interest_rates', 'channel')
    # ### end Alembic commands ###
