"""add column method into table rate_limits

Revision ID: 69b996924b96
Revises: 874a9ae1292a
Create Date: 2026-04-08 15:17:52.210191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b996924b96'
down_revision: Union[str, None] = '874a9ae1292a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_limits', sa.Column('method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_limits', 'method')
    # ### end Alembic commands ###
