"""create table ratelimit

Revision ID: 874a9ae1292a
Revises: 5880a845882a
Create Date: 2026-04-08 14:25:37.580111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874a9ae1292a'
down_revision: Union[str, None] = '5880a845882a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_limit_capacity', sa.Integer(), nullable=True),
    sa.Column('refill_rate', sa.Integer(), nullable=True),
    sa.Column('window_time', sa.Integer(), nullable=True),
    sa.Column('max_limit_second', sa.Integer(), nullable=True),
    sa.Column('max_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
