"""update add config ondelete for table interest_rates

Revision ID: 883647ab16b1
Revises: 3a5bbd8f5bc7
Create Date: 2026-04-02 02:16:43.784944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883647ab16b1'
down_revision: Union[str, None] = '3a5bbd8f5bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interest_rates', 'create_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('interest_rates_create_by_fkey', 'interest_rates', type_='foreignkey')
    op.create_foreign_key(None, 'interest_rates', 'users', ['create_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interest_rates', type_='foreignkey')
    op.create_foreign_key('interest_rates_create_by_fkey', 'interest_rates', 'users', ['create_by'], ['id'])
    op.alter_column('interest_rates', 'create_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
