"""fix foreignKey at userRole table

Revision ID: 8c704f023aa6
Revises: f88b81d0e36f
Create Date: 2026-03-30 01:07:29.179716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c704f023aa6'
down_revision: Union[str, None] = 'f88b81d0e36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_assigned_by_fkey', 'user_roles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_roles_assigned_by_fkey', 'user_roles', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###
