"""add table saving_plan

Revision ID: a79bea0c1254
Revises: 65ac863ab0f9
Create Date: 2026-05-14 02:07:36.236155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79bea0c1254'
down_revision: Union[str, None] = '65ac863ab0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banks_type_key', 'banks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('banks_type_key', 'banks', ['type'])
    # ### end Alembic commands ###
