"""update column relationship database

Revision ID: f88b81d0e36f
Revises: 1ec9b99480e5
Create Date: 2026-03-28 00:56:11.278108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88b81d0e36f'
down_revision: Union[str, None] = '1ec9b99480e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('user_roles', 'assigned_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'user_roles', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.alter_column('user_roles', 'assigned_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
